import { Condicion } from "./Condicion";
import { CteEnviarA } from "./CteEnviarA";
import { Descuento } from "./Descuento";

export interface Cliente {
    cliente?: string,
    rama?: string,
    nombre?: string,
    nombreCorto?: string,
    direccion?: string,
    direccionNumero?: string,
    direccionNumeroInt?: string|null,
    entreCalles?: string|null,
    delegacion?: string,
    colonia?: string,
    poblacion?: string,
    estado?: string,
    pais?: string,
    codigoPostal?: string,
    rfc?: string,
    telefonos?: string,
    telefonosLada?: string,
    sirac?: string|null,
    contacto1?: string,
    email1?: string,
    categoria?: string,
    grupo?: string,
    familia?: string,
    tipo?: string,
    descuento?: string,
    formaEnvio?: string|null,
    condicion?: string,
    ruta?: string,
    listaPreciosESP?: string,
    defMoneda?: string|null,
    agente?: string|null,
    estatus?: string,
    rCondicion?: Condicion|null,
    rDescuento?: Descuento|null,
    rCteEnviarA?: Array<CteEnviarA>|null,
    contrasena?: string|null,
    contrasena2?: string,
    eje?: string|null,
    limite?: number|null
}